use alloc::boxed::Box;
use alloc::collections::BTreeMap;
use alloc::vec::Vec;
use core::ops;
use core::ops::RangeInclusive;
use embedded_graphics::mono_font::mapping::{GlyphMapping, StrGlyphMapping};

/// ASCII space character offset for fast ASCII lookups
const ASCII_OFFSET: usize = *NamedUnicodeBlock::Ascii.range().start() as usize;

impl GlyphMapping for FontAtlas {
    /// Returns the glyph index for a character, falling back to index 0 (space) if not found
    fn index(&self, c: char) -> usize {
        self.find(c).unwrap_or(0)
    }
}

/// Font atlas containing Unicode blocks and additional symbols for efficient glyph lookup.
///
/// The atlas stores characters in two categories:
/// - Contiguous Unicode blocks (e.g., ASCII, Latin-1) for efficient range-based lookup
/// - Individual symbols stored separately and accessed via binary search
///
/// # Performance
/// - ASCII characters use a fast path with direct offset calculation
/// - Non-ASCII characters are looked up via binary search within blocks
/// - Memory usage is optimized for embedded systems
pub struct FontAtlas {
    blocks: Vec<UnicodeBlock>,
    other_symbols: BTreeMap<char, usize>,
}


impl FontAtlas {
    /// Returns the total number of glyphs in the atlas.
    pub fn glyph_count(&self) -> usize {
        self.glyph_count_in_blocks() + self.other_symbols.len()
    }

    /// Returns an iterator over all characters in the atlas.
    ///
    /// Unicode blocks are yielded first, followed by individual symbols.
    pub fn iter(&self) -> impl Iterator<Item=char> + '_ {
        self.blocks.iter()
            .flat_map(|b| b.iter()).chain(self.other_symbols.keys().copied())
    }

    /// Returns `true` if the atlas contains the given character.
    pub fn contains(&self, symbol: char) -> bool {
        self.blocks.iter().any(|b| b.contains(symbol))
            || self.other_symbols.contains_key(&symbol)
    }

    /// Finds the glyph index for a character.
    ///
    /// # Returns
    /// The glyph index if the character is in the atlas, `None` otherwise.
    pub fn find(&self, symbol: char) -> Option<usize> {
        // ca 70% faster with ASCII fast path in benchmarks
        if symbol.is_ascii() {
            return Some(symbol as usize - ASCII_OFFSET);
        }

        self.blocks
            .iter()
            .skip(1) // skip ASCII block, handled above
            .find_map(|b| b.try_index(symbol))
            .or_else(|| self.index_of_other_symbol(symbol))
    }

    /// Leaks the font atlas to obtain a 'static reference.
    ///
    /// # Safety
    /// This permanently leaks memory and should only be used when the atlas needs
    /// to live for the entire program duration.
    #[must_use]
    pub fn leak(self) -> &'static Self {
        // danger: leaking memory for the lifetime of the program
        Box::leak(Box::new(self))
    }

    /// Creates a font atlas from an iterator of character ranges.
    ///
    /// Ranges with multiple characters become Unicode blocks, while single-character
    /// ranges are stored as individual symbols.
    ///
    /// # Panics when debug assertions are enabled if:
    /// - If the first range doesn't start with ASCII space (U+0020)
    /// - If ranges are not sorted in ascending order
    /// - If individual symbols are not sorted in ascending order
    fn from_ranges(ranges: impl Iterator<Item=(usize, ops::RangeInclusive<char>)>) -> Self {
        let indexed_ranges: Vec<_> = ranges.collect();

        let blocks: Vec<_> = indexed_ranges.iter()
            .filter(|(_, range)| range_len(range) > 1)
            .cloned()
            .map(UnicodeBlock::from)
            .collect();

        let singles = indexed_ranges.iter()
            .filter(|(_, range)| range_len(range) == 1)
            .flat_map(|(offset, range)| range.clone().into_iter().map(|c| (c, *offset)))
            .collect::<BTreeMap<_, _>>();

        debug_assert!(
            blocks[0].start() == '\u{0020}',
            "Invalid FontAtlas: must start with ASCII block"
        );

        debug_assert!(
            blocks.windows(2).all(|w| w[0].start() < w[1].start()),
            "Invalid FontAtlas: ranges must be sorted"
        );

        Self {
            blocks,
            other_symbols: singles,
        }
    }

    pub fn glyph_count_in_blocks(&self) -> usize {
        self.blocks
            .last()
            .map(|b| b.len() + b.base_offset as usize)
            .unwrap_or(0)
    }

    fn index_of_other_symbol(&self, symbol: char) -> Option<usize> {
        self.other_symbols.get(&symbol).copied()
    }
}

impl From<&str> for FontAtlas {
    /// Creates a font atlas from a string containing all required characters.
    /// This assumes the input string is sorted and contains the ASCII range,
    /// which is what is generated by the `bdf-atlas-converter` tool.
    ///
    /// Uses [`StrGlyphMapping`] to extract character ranges from the input string.
    fn from(glyph_set: &str) -> Self {
        Self::from_ranges(StrGlyphMapping::new(glyph_set, 0).ranges())
    }
}

/// Internal representation of a Unicode block with base offset for glyph indexing.
#[derive(Debug, Clone)]
struct UnicodeBlock {
    base_offset: u32,
    range: ops::RangeInclusive<char>,
}

impl UnicodeBlock {
    fn contains(&self, symbol: char) -> bool {
        let c = symbol as u32;
        c <= *self.range.end() as u32 && c >= *self.range.start() as u32
    }

    /// Returns the glyph index for the symbol if it's in this block
    fn try_index(&self, symbol: char) -> Option<usize> {
        if self.contains(symbol) {
            let offset = symbol as usize - *self.range.start() as usize;
            Some(self.base_offset as usize + offset)
        } else {
            None
        }
    }

    fn len(&self) -> usize {
        range_len(&self.range) as usize
    }

    /// Iterates over all characters in the atlas
    fn iter(&self) -> impl Iterator<Item=char> + '_ {
        self.range.clone()
    }

    fn start(&self) -> char {
        *self.range.start()
    }

}

/// Named Unicode blocks with predefined ranges for font generation
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum NamedUnicodeBlock {
    Ascii,            // 0x0020..=0x007F
    Latin1,           // 0x00A0..=0x00FF
    BlockElements,    // 0x2580..=0x259F
    BoxDrawing,       // 0x2500..=0x257F
    Miscellaneous,    // 0x2600..=0x26FF
    BraillePatterns,  // 0x2800..=0x28FF
    CurrencySymbols,  // 0x20A0..=0x20CF
    Dingbats,         // 0x2700..=0x27BF
    SymbolsAndArrows, // 0x2B00..=0x2BFF
    TransportAndMap,  // 0x1F680..=0x1F6FF
    Pictographs,      // 0x1F300..=0x1F5FF
}

impl NamedUnicodeBlock {
    /// Returns the Unicode range for this block
    pub const fn range(&self) -> ops::RangeInclusive<char> {
        match self {
            Self::Ascii            => '\u{0020}'..='\u{007E}',
            Self::Latin1           => '\u{00A0}'..='\u{00FF}',
            Self::BoxDrawing       => '\u{2500}'..='\u{257F}',
            Self::BlockElements    => '\u{2580}'..='\u{259F}',
            Self::Miscellaneous    => '\u{2600}'..='\u{26FF}',
            Self::BraillePatterns  => '\u{2800}'..='\u{28FF}',
            Self::CurrencySymbols  => '\u{20A0}'..='\u{20CF}',
            Self::Dingbats         => '\u{2700}'..='\u{27BF}',
            Self::SymbolsAndArrows => '\u{2B00}'..='\u{2BFF}',
            Self::Pictographs      => '\u{1F300}'..='\u{1F5FF}',
            Self::TransportAndMap  => '\u{1F680}'..='\u{1F6FF}',
        }
    }
}



fn range_len(range: &ops::RangeInclusive<char>) -> u32 {
    *range.end() as u32 - *range.start() as u32 + 1
}

impl From<(usize, ops::RangeInclusive<char>)> for UnicodeBlock {
    fn from((base_offset, range): (usize, RangeInclusive<char>)) -> Self {
        Self {
            base_offset: base_offset as u32,
            range,
        }
    }
}